# Generated by Django 5.2.7 on 2025-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Public contact email (different from login email)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Website or social media URL", null=True
            ),
        ),
    ]
