# Generated by Django 5.2.7 on 2025-10-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_contact_email_user_contact_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
