# Generated by Django 5.2.7 on 2025-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Biografia do usuário", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail de contato público (diferente do e-mail de login)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Número de telefone de contato",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Website ou URL de rede social", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil do usuário",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]


# Generated by Django 5.2.7 on 2025-11-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Biografia do usuário", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail de contato público (diferente do e-mail de login)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Número de telefone de contato",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_website",
            field=models.URLField(
                blank=True, help_text="Website ou URL de rede social", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil do usuário",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
