# Generated by Django 5.2.7 on 2025-10-21 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("event", "Event"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or emoji", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="News or event title", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full content of the news or event"),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary for listings (max 300 chars)",
                        max_length=300,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Main image for the news/event",
                        null=True,
                        upload_to="news/%Y/%m/",
                    ),
                ),
                (
                    "image_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for featured image",
                        max_length=200,
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of event (for events only)",
                        null=True,
                    ),
                ),
                (
                    "event_location",
                    models.CharField(
                        blank=True,
                        help_text="Location of event (for events only)",
                        max_length=200,
                    ),
                ),
                (
                    "event_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="End date and time of event (optional)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when this should be published",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured/highlighted sections"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this has been viewed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who created this news/event",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Type of content (news, event, announcement)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_items",
                        to="news.newscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "News/Event",
                "verbose_name_plural": "News/Events",
                "ordering": ["-publish_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-publish_date"],
                        name="news_news_status_f9f45e_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="news_news_categor_caf58c_idx",
                    ),
                    models.Index(fields=["slug"], name="news_news_slug_915ecd_idx"),
                    models.Index(
                        fields=["-publish_date"], name="news_news_publish_3b3118_idx"
                    ),
                ],
            },
        ),
    ]
