# Generated by Django 5.2.7 on 2025-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscategory",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Classe de ícone ou emoji", max_length=50
            ),
        ),
    ]
