# Generated by Django 5.2.7 on 2025-11-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em Progresso", "Em Progresso"),
                    ("Publicado", "Publicado"),
                    ("Arquivado", "Arquivado"),
                ],
                default="Em Progresso",
                help_text="Publication status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                help_text="Titulo da noticia ou evento", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Icone ou emoji", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("Noticias", "Noticias"),
                    ("Evento", "Eventos"),
                    ("Anuncios", "Anuncios"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
