# Generated by Django 5.2.7 on 2025-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_status_alter_news_title_and_more"),
        ("news", "0002_alter_newscategory_icon"),
    ]

    operations = []
