# Generated by Django 5.2.7 on 2025-11-10 01:26

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default news categories if they don't exist"""
    NewsCategory = apps.get_model("news", "NewsCategory")

    categories = [
        {
            "name": "Noticias",
            "description": "Notícias gerais sobre Maricá",
            "icon": "📰",
        },
        {
            "name": "Evento",
            "description": "Eventos e atividades em Maricá",
            "icon": "📅",
        },
        {
            "name": "Anuncios",
            "description": "Anúncios oficiais e comunicados",
            "icon": "📢",
        },
    ]

    for cat_data in categories:
        NewsCategory.objects.get_or_create(
            name=cat_data["name"],
            defaults={
                "description": cat_data["description"],
                "icon": cat_data["icon"],
            },
        )


def reverse_func(apps, schema_editor):
    """No-op reverse function (categories are safe to keep)"""


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newscategory_icon"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_func),
    ]
