# Generated by Django 5.2.7 on 2025-10-14 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly category identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for the category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the category is currently active')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which category appears (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='explore_cat_is_acti_97a474_idx'), models.Index(fields=['slug'], name='explore_cat_slug_f44964_idx')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the place', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the place')),
                ('address', models.TextField(help_text='Full address of the place')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('contact_website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the place has been approved by admin')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the place is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this place belongs to', related_name='places', to='explore.category')),
                ('created_by', models.ForeignKey(help_text='User who created this place', on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REQUEST_CHANGES', 'Request Changes')], help_text='Action taken by the reviewer', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Reviewer comments or feedback')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, help_text='When the review was conducted')),
                ('place', models.ForeignKey(help_text='Place being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='explore.place')),
                ('reviewer', models.ForeignKey(help_text='Admin user who reviewed the place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Place Approval',
                'verbose_name_plural': 'Place Approvals',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Place image', upload_to='places/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Image caption or description', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary/main image for the place')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which image appears in gallery (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
                ('place', models.ForeignKey(help_text='Place this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='explore.place')),
            ],
            options={
                'verbose_name': 'Place Image',
                'verbose_name_plural': 'Place Images',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_approved', 'is_active'], name='explore_pla_is_appr_02eda9_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-created_at'], name='explore_pla_created_6d6db1_idx'),
        ),
        migrations.AddIndex(
            model_name='placeapproval',
            index=models.Index(fields=['place', '-reviewed_at'], name='explore_pla_place_i_54b718_idx'),
        ),
        migrations.AddIndex(
            model_name='placeapproval',
            index=models.Index(fields=['reviewer', '-reviewed_at'], name='explore_pla_reviewe_ba6a17_idx'),
        ),
        migrations.AddIndex(
            model_name='placeapproval',
            index=models.Index(fields=['action'], name='explore_pla_action_2f893f_idx'),
        ),
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['place', 'display_order'], name='explore_pla_place_i_03c76b_idx'),
        ),
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['place', 'is_primary'], name='explore_pla_place_i_130757_idx'),
        ),
    ]
