# Generated by Django 5.2.7 on 2025-10-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="place",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="place",
            name="contact_website",
        ),
        migrations.RemoveField(
            model_name="place",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="place",
            name="longitude",
        ),
    ]
