# Generated by Django 5.2.7 on 2025-10-18 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0002_remove_place_contact_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Review comment/feedback", max_length=1000
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.ForeignKey(
                        help_text="Place being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="explore.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who wrote the review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Place Review",
                "verbose_name_plural": "Place Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["place", "-created_at"],
                        name="explore_pla_place_i_10282d_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="explore_pla_user_id_8d0a93_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="explore_pla_rating_dcb945_idx"
                    ),
                ],
                "unique_together": {("place", "user")},
            },
        ),
    ]
