# Generated by Django 5.2.7 on 2025-10-18 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0003_placereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        help_text="Place that was favorited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="explore.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who favorited the place",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="explore_fav_user_id_ac949b_idx",
                    ),
                    models.Index(
                        fields=["place"], name="explore_fav_place_i_b01c2b_idx"
                    ),
                ],
                "unique_together": {("user", "place")},
            },
        ),
    ]
