# Generated by Django 5.2.7 on 2025-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0004_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
    ]
