# Generated by Django 5.2.7 on 2025-11-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0005_place_latitude_place_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
            },
        ),
        migrations.AlterModelOptions(
            name="placeapproval",
            options={
                "ordering": ["-reviewed_at"],
                "verbose_name": "Aprovação de Lugar",
                "verbose_name_plural": "Aprovações de Lugares",
            },
        ),
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["display_order", "-uploaded_at"],
                "verbose_name": "Imagem do Lugar",
                "verbose_name_plural": "Imagens do Lugar",
            },
        ),
        migrations.AlterModelOptions(
            name="placereview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Avaliação de Lugar",
                "verbose_name_plural": "Avaliações de Lugares",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, help_text="Descrição da categoria"),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Ordem em que a categoria aparece (números menores primeiro)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Classe do ícone ou emoji para a categoria",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Se a categoria está atualmente ativa"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Nome da categoria", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Identificador amigável para URL", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="place",
            field=models.ForeignKey(
                help_text="Lugar que foi favoritado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="explore.place",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                help_text="Usuário que favoritou o lugar",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.TextField(help_text="Endereço completo do lugar"),
        ),
        migrations.AlterField(
            model_name="place",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categorias às quais este lugar pertence",
                related_name="places",
                to="explore.category",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="created_by",
            field=models.ForeignKey(
                help_text="Usuário que criou este lugar",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(help_text="Descrição detalhada do lugar"),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Se o lugar está atualmente ativo"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Se o lugar foi aprovado pelo administrador"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Coordenada de longitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(help_text="Nome do lugar", max_length=200),
        ),
        migrations.AlterField(
            model_name="placeapproval",
            name="action",
            field=models.CharField(
                choices=[
                    ("APPROVE", "Aprovado"),
                    ("REJECT", "Rejeitado"),
                    ("REQUEST_CHANGES", "Solicitar Alterações"),
                ],
                help_text="Ação realizada pelo revisor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="placeapproval",
            name="comments",
            field=models.TextField(
                blank=True, help_text="Comentários ou feedback do revisor"
            ),
        ),
        migrations.AlterField(
            model_name="placeapproval",
            name="place",
            field=models.ForeignKey(
                help_text="Lugar sendo revisado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_history",
                to="explore.place",
            ),
        ),
        migrations.AlterField(
            model_name="placeapproval",
            name="reviewed_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Quando a revisão foi realizada"
            ),
        ),
        migrations.AlterField(
            model_name="placeapproval",
            name="reviewer",
            field=models.ForeignKey(
                help_text="Usuário administrador que revisou o lugar",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="place_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="caption",
            field=models.CharField(
                blank=True, help_text="Legenda ou descrição da imagem", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Ordem em que a imagem aparece na galeria (números menores primeiro)",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="image",
            field=models.ImageField(
                help_text="Imagem do lugar", upload_to="places/images/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Se esta é a imagem principal/primária do lugar",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                help_text="Lugar ao qual esta imagem pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="explore.place",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Quando a imagem foi carregada"
            ),
        ),
        migrations.AlterField(
            model_name="placereview",
            name="comment",
            field=models.TextField(
                help_text="Comentário/feedback da avaliação", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="placereview",
            name="place",
            field=models.ForeignKey(
                help_text="Lugar sendo avaliado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="explore.place",
            ),
        ),
        migrations.AlterField(
            model_name="placereview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Estrela"),
                    (2, "2 Estrelas"),
                    (3, "3 Estrelas"),
                    (4, "4 Estrelas"),
                    (5, "5 Estrelas"),
                ],
                help_text="Avaliação de 1 a 5 estrelas",
            ),
        ),
        migrations.AlterField(
            model_name="placereview",
            name="user",
            field=models.ForeignKey(
                help_text="Usuário que escreveu a avaliação",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place_reviews_written",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
