# Generated by Django 5.2.7 on 2025-11-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0006_alter_category_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="placereview",
            unique_together=set(),
        ),
    ]
